### ISSUE TITLE
Implementing GUI for making hydra vocab and visualising it 

### ISSUE THREAD

**Issue by vaibhavchellani** [HTTP-APIs/python-hydra-agent#1]
from [HTTP-APsI/hydrus#158](https://github.com/HTTP-APIs/hydrus/issues/158)

There are two things that can be done here -

Create a GUI to help users set up vocabulary. Users use the GUI to describe the API structure and the GUI then spits out a hydra vocabulary file which can then be used to setup hydrus.

The other thing that can be done is use the GUI to load already created vocabularies and visualise it. Allowing the users to easily modify and play with the API structure that the vocabulary will create.

I would like to work on this .
@Mec-iS @xadahiya @chrizandr   how should i proceed ? What is expected out of this ?

**Comment by Mec-iS** [comment]
I found it interesting especially if you can set in place a good parser. The way to go is to write a proposal that includes this idea.

**Comment by suryatejreddy** [comment]
@Mec-iS adding to the discussion in HTTP-APIs/hydrus#149, the `hydra -> OpenAPI` parser can be used to visualize the `API doc` taking inspiration from SwaggerHub. Because `OpenAPI` is very basic in specification and major part of it is `/path` objects that define operations (get,post,put,delete).

**Comment by ashwani99** [comment]
We can use RDFlib's inbuilt parser to parse through the APIDocumentation. It supports several formats like xml, n3, ntriples, trix, json-ld etc

**Comment by Mec-iS** [comment]
Yea, we can use a standard JSON-LD parser. We don't want to reinvent the wheel.

**Comment by suryatejreddy** [comment]
Okay makes sense. I'll integrate this into my proposal. thanks @ashwani99 and @Mec-iS .

**Comment by xadahiya** [comment]
Not relevant to the agent.
