### ISSUE TITLE
Representation of API graph on Redis Datastore.

### ISSUE THREAD

**Issue by chrizandr** [HTTP-APIs/python-hydra-agent#11]
When a client wants to use an API, it stores that APIs graph in Redis for better querying and optimization. 

We need to figure out what representation of the API Graph is best for querying as well as efficient for implementation. 

Add comments about possible representations. Keep in mind that the end goal here is to be able to match the API representations to request objects without having to explicitly use URIs.

**Comment by Mec-iS** [comment]
Just a note: the graph is built from the ApiDoc but it needs also to be updated according to subsequent data reads from the server. For example, if a `Book` object with id 1 holds a property `hasAuthor` that can be referenced to an `Author` object with id 3, the graph should store a node book-1 with a named edge to author-3. This way the client holds the structure/abstraction of the data (technically metadata) while the actual data (the full objects) are held and requested from the server.

**Comment by chrizandr** [comment]
Agreed. The datastore basically acts like a cache for the API server. It does local computation to find the correct mapping for the requested objects. It needs to be dynamic enough to change as the server data changes.

**Comment by xadahiya** [comment]
@sandeepsajan0 You should start with a basic setup first. Within the next 2-3 days, you should finish at least these 3. 
- We need a client that can be connected to one or multiple servers (this can be done later, for now, you can focus on connecting to a single server)
- It should be able to fetch the APIdoc from the server
- Redis should be up and running ( This should preferably be done in a  Docker/Vagrant environment). We fire up the VM instance with everything set up like Redis and other required packages.

Once this is done then you can focus on loading the APIDoc in memory (in Redis). This is where the [hydra-py](https://github.com/pchampin/hydra-py) comes in the picture. Use it to understand how APIDoc is being loaded in python stack and then try to implement similar functionality for Redis. Performance and model improvements can be done along the way. You should be able to query the available types from the APIDoc.
Then we can discuss ways for the client to fetch additional required data from the servers and update its graph.

**Comment by sandeepsajan0** [comment]
@xadahiya Some of the work is done by me which you have mentioned above. I am able to fetch the APIdoc from the server and I have a set up of Redis locally on my pc(later I will set an environment using Docker). 
And I have struct a graph which is using nodes and edges to store data as triples. I have got some idea from [here](https://docs.google.com/document/d/1FMhqovdylJ0kbtDGuuQDfISXgmm2c6vDDB5ILGT9-Ww/edit) and [here](https://github.com/HTTP-APIs/hydra-ecosystem-wiki/blob/master/Design.md#multi-layered-database-design). I am starting its implementation. Its implementation can take the time of a week.

**Comment by sandeepsajan0** [comment]
I think it can be closed because we have one more issue related to this #18 .
