### ISSUE TITLE
Create a Docker/Vagrant env for the agent

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/python-hydra-agent#12]
As the Hydra Agent will use Redis, we need a VM environment with everything set up. ( I personally vote for Docker. It has a lot of configuration options. Also, it's quite lightweight.)

**Comment by sandeepsajan0** [comment]
@xadahiya  For now, I am using Redis locally(with my local env) but on later I will set the Docker environment.

**Comment by xadahiya** [comment]
Okay, no problem. In that case make sure you provide a configuration file for us to set up the redis datastore for testing.

**Comment by Mec-iS** [comment]
Use `docker-compose` to set up two different containers

**Comment by sandeepsajan0** [comment]
fixed in #46  and #47
