### ISSUE TITLE
Error Using python-agent with docker

### ISSUE THREAD

**Issue by Purvanshsingh** [HTTP-APIs/python-hydra-agent#160]
### I'm submitting a 
- [x] bug report.
- [ ] feature request.

### Current Behaviour:

**TypeError: a bytes-like object is required, not 'str'** on running `sudo docker-compose run client`

### Steps to reproduce:

`sudo docker-compose run client`

OS: Ubuntu 20.04
docker-compose version 1.25.0

**Comment by Purvanshsingh** [comment]
![Uploading Screenshot from 2021-01-19 10-53-04.png…]()

**Comment by Purvanshsingh** [comment]
![Screenshot from 2021-01-19 10-53-04](https://user-images.githubusercontent.com/49719371/104991450-ce477e80-5a44-11eb-8bf6-c36a453251a6.png)

**Comment by raoashish10** [comment]
@Purvanshsingh I tried replicating the issue but I didn't encounter any such error. Have you made any changes to the code?

**Comment by Purvanshsingh** [comment]
Nope, I didn't make any changes in the code.

**Comment by raoashish10** [comment]
I am running the command on a similar environment:
OS: Ubuntu 20.04
docker-compose: 1.25.5 
Maybe someone else who can replicate the issue can try solving. Try updating the docker-compose version, might help?

**Comment by Purvanshsingh** [comment]
Fixed docker-compose should be of the latest stable version.
