### ISSUE TITLE
Migrate test suite from unittest to pytest

### ISSUE THREAD

**Issue by amalthundiyil** [HTTP-APIs/python-hydra-agent#169]
### I'm submitting a 
- [ ] bug report.
- [x] feature request.

### Current Behaviour:
The test suite for `hydra-python-agent` is written using `unittest` library.

### Expected Behaviour:
I feel that using `pytest` would improve the readability of the test code with its features like fixtures, mocks, etc. As `hydra-python-agent` continues to grow and get refactored, this could be worth a consideration.

### Do you want to work on this issue?

Yes

**Comment by Mec-iS** [comment]
ok, please provide a PR and we will take time to review it
