### ISSUE TITLE
Move the code for python-hydra-agent to a separate directory.

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/python-hydra-agent#17]
You should move the code you're writing for python-hydra-agent to a new directory away from hydra-py code unless you're using hydra-py in some way which I think you're not. 
Create a new directory and move all your code there.

**Comment by sandeepsajan0** [comment]
Done! now, it is moved to hydra_redis directory.

**Comment by xadahiya** [comment]
You should make it `hydra-redis` instead of `hydra_redis`
