### ISSUE TITLE
Graph structure for Redis

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/python-hydra-agent#18]
Discussion related to the Graph structure we need for storing the parsed data as well as the API structure for python-hydra-agent.

**Comment by xadahiya** [comment]
**THIS IS FROM SANDEEP'S DOC**
![selection_024](https://user-images.githubusercontent.com/9114274/40872607-924712f0-666e-11e8-8acc-c2de1d1c94b5.png)
**Graph**:
First we have node of EntryPoint from where we can access any data stored in graph. Then graph have two types of nodes collection endpoint node and classes endpoint node. Assume that collection endpoint contains DroneCollection and CommandCollection. So, we have nodes for them and if there will be other collections then graph will make the nodes for that also automatically(no. of collection nodes depends on the no of collection endpoints in apidoc)  and then we have to access its objects like Drone1 for drone collection and graph have node for every property of object that have other properties in itself like Drone1State.
For the classes endpoint graph have the node for every object store in classes endpoint and also for that property which have property in it also.   
Connections for the graph is shown above.

**Add or delete nodes or operation perform:**
Every node in graph have its own properties in which most of the nodes have a property of method(operation).  Any operation can be done with add and delete the node.

Google Doc link: https://docs.google.com/document/d/1iQ-0UwRyrePVrmW9z7AuUyK6TiilMIimlhn9msRH3eI/edit

**Comment by xadahiya** [comment]
**A basic structure I proposed**

![img_20180602_135101](https://user-images.githubusercontent.com/9114274/40872625-0cf202b2-666f-11e8-9e51-fdc717d4642b.jpg)

**Note: We're using the drone API as an example.**

**Comment by xadahiya** [comment]
@Mec-iS @chrizandr @Shekharrajak  Please provide your opinions

**Comment by sandeepsajan0** [comment]
@xadahiya, I think the above one(mine) graph structure works similar to yours but in mine graph structure I have some more functionality like connected edges like Drone1 to entrypoint which will help in fast and easy querying. We can access any Drone or Command Object directly and In every node there(in code) is a property part which has all the property for the node as an object and if any property has object in it then graph consider it as a different node with its own property and we can access this property recursively.

**Comment by sandeepsajan0** [comment]
Yeah @xadahiya, Now I got your point. I have updated the graph here https://docs.google.com/document/d/1iQ-0UwRyrePVrmW9z7AuUyK6TiilMIimlhn9msRH3eI/edit?usp=sharing.

**Comment by chrizandr** [comment]
@sandeepsajan0 The edge names can be the same as the name of the property, you don't need to create new names for connections. Also, if they have the same `MaxSpeed` you don't need an edge between the two drones. Just one node for an instance of `MaxSpeed` and two incoming edges to that node, from the two different drones. The name of the edge will be the property of the two drones that references `MaxSpeed`. For example, if there is a property called `Address` having an object that is of type `GeoCoordinates`, then you will have an instance of a `GeoCoordinates` object and an edge called `Address` connecting to that instance. If multiple items use that `GeoCoordinates` instance, then you need to have multiple incoming edges on that one instance. 

It is important that you **do not** create additional nodes/edges that are not already present in the API, this can make things unnecessarily complicated and it might be very difficult to change such a structure at a later phase. Stick the API structure and use that only to create the graph.

**Comment by xadahiya** [comment]
This is related to the review I just did https://github.com/HTTP-APIs/python-hydra-agent/pull/13#pullrequestreview-126615225 .
@sandeepsajan0 You're storing some redundant information. Here's a detailed graph structure for you to work on.
![img_20180607_093323](https://user-images.githubusercontent.com/9114274/41077769-3993c998-6a36-11e8-84d7-878ebf2f69a5.jpg)
![img_20180607_093345](https://user-images.githubusercontent.com/9114274/41077776-46cfa5fa-6a36-11e8-9824-033555b4e868.jpg)
![img_20180607_093407](https://user-images.githubusercontent.com/9114274/41077777-472ab45e-6a36-11e8-8a25-292f44d07fcc.jpg)
![img_20180607_093423](https://user-images.githubusercontent.com/9114274/41077778-4776e9f0-6a36-11e8-8613-9238e63587d7.jpg)

@chrizandr  @Mec-iS @kkoci  Please add if I missed something.
