### ISSUE TITLE
Implement a querying mechanism for loaded Graph

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/python-hydra-agent#20]
Write a querying mechanism to extract information from the graph loaded in memory. Redis uses `openCypher` by default. I'm not sure if `redis-py` can be used for querying purposes, explore different options and write their pros and cons below.
Some helpful resources - 
- https://oss.redislabs.com/redisgraph/design/#graph-representation-hexastore
- http://pythonik.blogspot.com/2010/11/redis-patterns-search.html

**Comment by sandeepsajan0** [comment]
I think we can access the redisgraph's all functionality with its any client https://oss.redislabs.com/redisgraph/#using-redis-graph
I will take some help with these commands https://oss.redislabs.com/redisgraph/commands/#query-language.

**Comment by sandeepsajan0** [comment]
Can you elaborate for me a bit with an example that how I should proceed for querying mechanism?
And also suggests some things which should be mind for querying.

**Comment by xadahiya** [comment]
> And also suggests some things which should be mind for querying.

Consider the drone API example. User can query for all drones with `max_speed > 100` or drones with `battery > 30%`.
The user should also be able to query all API endpoints, class endpoints, collection endpoints etc. 
He should also be able to view all supported properties for each endpoint object for example in case of drone demo he should be able to query and view all `supportedProperties` and `supportedOperations` for the drone and all other endpoints.

**Note** - We'll also need to add functionality to make requests to the server in order to add/modify/delete data but this can be done later. You should design the agent keeping this in mind though.

The querying format and implementation part is up to you. Do some research and discuss possible options or ideas you have in mind here.

**Comment by sandeepsajan0** [comment]
Querying format:

For querying endpoints- `url:endpoint`, `url:entrypoint`, `url:endpoint:id` and etc like these(here id is just refer to the member of any collection endpoint).

For querying operation or property- `url:endpoint:operation`, `url:endpoint:property`, `url:endpoint:propValue`, and same for id(members) and etc like these( operation = supportedOperation and property = supportedProperty and propValue  = supportedProperty with its values).

For querying with comparison(like `max_speed > 100`)- `url:endpoint:propCompare`, `url:endpoint:propCompare1:and:propComp2`,  and more like these(propCompare can be stored in a list with `and` and `or` in same order as user input).

Benefit of this format: 
1. We need url for fetch or load the information.
2. We can also get url for any endpoint  with the help of `url` and `endpoint`.
3. We can easily handle with the comparison of supported property like `max_speed > 100` and other.

Execution process:
Every time when user querying, we have a check for the same `url` and `endpoint` of its existence in Redis. If it exists in Redis then we can direct query from Redis but if it does not exist in Redis we have load data from the server to Redis for the same endpoint and then query from the Redis. 

Please share your opinion on this and suggest required changes.

**Comment by xadahiya** [comment]
Implemented in #23
