### ISSUE TITLE
Design faceted indexes alongside with the usage of the GraphLib

### ISSUE THREAD

**Issue by sandeepsajan0** [HTTP-APIs/python-hydra-agent#27]
We have to design faceted indexes for better search in Redis memory.

Here we'll indexing for every node and its properties based on an object.

DroneCollection indexing can be like:
` fs:DroneCollection    {.....}`

and for its member like /DroneCollection/2
` fs:DroneCollection Drone2    {.....}`

Here we can store an object with a key, It is not the exact way of indexing it'll update below comments.
 
Probably, We'll use the hash data structure for it because it can store many fields which can be the properties of endpoints.
@Mec-iS , @xadahiya , @chrizandr  Please share your opinion.

**Comment by Mec-iS** [comment]
Main themes to focus on:
* how to find out which properties to index (required?)?
* how to build composite indexes and with which properties?

**Comment by sandeepsajan0** [comment]
@xadahiya  we need to do something in this or we can be closed it?
