### ISSUE TITLE
Installation using pip install  gives FileNotFoundError

### ISSUE THREAD

**Issue by suryatejreddy** [HTTP-APIs/python-hydra-agent#4]
The following error is encountered while installing with `pip install .`. 
![image](https://user-images.githubusercontent.com/21313201/37571908-1ba7c822-2b29-11e8-800a-da82fe2789af.png)

This is because setup.py expects a directory structure as `lib/hydra` whereas the structure in the current repository is just `hydra`. 
https://github.com/HTTP-APIs/python-hydra-agent/blob/925f6277649eb16087c4c95ebea3aa2c3011f9d6/setup.py#L11 

Can be solved by changing directory structure and modifying the `gitignore` to include `lib/hydra`

**Comment by Mec-iS** [comment]
Thanks. Try now on the develop branch.

**Comment by suryatejreddy** [comment]
@Mec-iS ,it works now. Should I close #5 ?

**Comment by Mec-iS** [comment]
https://github.com/HTTP-APIs/python-hydra-agent/commit/57da1389cebac5c6eea60a2c69b0288e6fe697b7
