### ISSUE TITLE
Agent has to be aligned with test cases in Draft

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/python-hydra-agent#54]
The agent has to be fully compliant with the interface and usage patterns as described in the [Draft's test cases](https://github.com/HydraCG/Specifications/blob/master/drafts/use-cases).

Provide a list of agent's API calls that are aligned or misaligned wit the Draft.

**Comment by PrajwalM2212** [comment]
@Mec-iS @xadahiya  I have made a list at https://github.com/PrajwalM2212/W3C-Hydra-Research to help me research ideas and to keep track. 
What should I do after this ? 
Should I start researching about how to implement ?

**Comment by Mec-iS** [comment]
moved to #61 so to have a more practical objective
