### ISSUE TITLE
Set up travis CI 

### ISSUE THREAD

**Issue by PrajwalM2212** [HTTP-APIs/python-hydra-agent#60]
It would be helpful to have travis CI setup on this project.

**Comment by Mec-iS** [comment]
@xadahiya if this possible to do before next year GSOC would be great. Thanks

**Comment by xadahiya** [comment]
Will do. Give me a couple of days, little busy right now 😅

**Comment by Mec-iS** [comment]
Sure. I am on annual leave so I am taking all the time to set up everything for next year!

**Comment by xadahiya** [comment]
Done!
