### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by xadahiya** [HTTP-APIs/python-hydra-agent#66]
Tests are failing for python-hydra-agent. All tests should pass
@sandeepsajan0

**Comment by de-sh** [comment]
Which one is this about?

**Comment by de-sh** [comment]
This is an issue with the absence of redis module.

**Comment by sandeepsajan0** [comment]
Sorry @xadahiya for the delay, I was not available due to some personal issues. But the main thing that we have already discussed, we don't have static live data. And for testing, we need some static live data. I can make all tests pass temporarily. But I think, now we should make these things permanent. So, tell me what should I do, make all test case pass temporarily or try to set up a live static data server.

**Comment by Mec-iS** [comment]
If you refer to https://travis-ci.com/HTTP-APIs/python-hydra-agent
The tests are failing because the `redis` Python package is missing.

**Comment by invinciblycool** [comment]
Apparently travis never runs `pip install -r requirements.txt`

**Comment by PrajwalM2212** [comment]
@invinciblycool  The requirements are installed by travis when it runs `pip install -e.`

**Comment by invinciblycool** [comment]
AFAIK, the `-e` flag is used to build packages from source.

**Comment by PrajwalM2212** [comment]
@invinciblycool In `setup.py` you can see `install_requires = parse_requirements('requirements.txt', session=PipSession())` . When you run `pip install -e.` it will install everything present in `install_requires`. So `install_requires` as you see is nothing but `requirements.txt`. 

The only change `-e ` gives you is that it will allow you edit your code and see changes in effect.

**Comment by invinciblycool** [comment]
I missed the setup.py. Makes sense :+1:

**Comment by PrajwalM2212** [comment]
Based on my observation the tests are failing for 
1. https://storage.googleapis.com/api4/api 
2. https://github.com/HTTP-APIs/python-hydra-agent/pull/73

**Comment by Mec-iS** [comment]
@sandeepsajan0 unit tests cannot depend from external services, tests shall use *patching* or *mocking* https://www.toptal.com/python/an-introduction-to-mocking-in-python

**Comment by Mec-iS** [comment]
615dbb2
