### ISSUE TITLE
Error when running redis_setup.sh in command line

### ISSUE THREAD

**Issue by krritik** [HTTP-APIs/python-hydra-agent#80]
when I run ./redis_setup.sh
it showed following error
"./redis_setup.sh: line 4: [: too many arguments
Docker is already installed" 
even when docker is not installed 
it is due to an error in argument of if-else in line 4

**Comment by Mec-iS** [comment]
@sandeepsajan0 installing Docker should not be done by this repo. A simple message "Docker is not installed" is enough. Plus, everything should be running using `docker-compose`, having `docker` and `docker-compose` installed is a pre-assumption and the repo should not take care of it.

**Comment by Mec-iS** [comment]
the environment already runs with `docker-compose`. Unused scripts shall be removed and the README updated. the only way to run the repo shall be `docker-compose`.
