### ISSUE TITLE
Mocking is done improperly

### ISSUE THREAD

**Issue by vddesai1871** [HTTP-APIs/python-hydra-agent#88]
## Current Behaviour:
Mocking is being done improperly.
```python
        check_data = [['p.properties', 'p.id', 'p.type'],
                      ["['Location']",'vocab:EntryPoint/Location','Location']]
        query = "show classEndpoints"
        EndpointQuery_get_classEndpoints = MagicMock(return_value=check_data)
        data = EndpointQuery_get_classEndpoints(query)
        print("testing classEndpoints...")
assert data == check_data
```
Correct me if I am missing something, but it seems like this test will always pass, same goes for all the tests. I can't understand why are we mocking Queries?
## Expected Behaviour:
As far as I know we are using moking so we can test the code without calling an actual (server) API, in that case I think we should only mock calls to the server(`url.get()`).

**Comment by vddesai1871** [comment]
@sandeepsajan0 you should assign this issue to someone else as because of exams I won't be able to work on anything before 17th March. And I think this is an important issue and should be solved as early as possible. And I also think we should not merge anymore PRs until we have working tests in place.

**Comment by ShravanDoda** [comment]
@sandeepsajan0 can I do it?

**Comment by sandeepsajan0** [comment]
@ShravanDoda Go for it.
