### ISSUE TITLE
Documentation for the datastore-client

### ISSUE THREAD

**Issue by Mec-iS** [HTTP-APIs/python-hydra-agent#9]
Fork https://github.com/HTTP-APIs/hydra-ecosystem-wiki and add a `PY-HYDRA-AGENT.md` file where to summarize the discussion we had during the Community Bonding phase. To be update as development goes on.

In the beginning this may include some of the content that you plan to write in the blog post.

**Comment by Mec-iS** [comment]
NOTE: adding to what we discussed, it is possible to explore also other options.
For example, as the graph representation may or may not change at every request issued by the agent in the case of changes in the `ApiDoc` or in the objects, we may think also about some event-driven ([event sourcing](https://stackoverflow.com/questions/28667367/best-event-sourcing-db-strategy)) kind of storing solution beside of a graph structure. Feel free to research in these days.

**Comment by xadahiya** [comment]
Moved to #22, #24 and #27
